[package]
name = "solarweb_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
